### ISSUE TITLE
Pr2: la función `agregarAlFinal` no está hecha con recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#10]
Toda la idea de esta práctica es usar recursión estructural, por lo que la solución ofrecida es inadecuada.

Por otra parte, en esta definición, la ecuación 1 es innecesaria, porque está cubierta por la siguiente. Si vas a hacer una solución con subtareas, no deberías mirar casos particulares...

**Comment by ramirez7358** [comment]
Elimine la que no usaba recursion estructural.

0bda335c0075d0d49a55fb3a93e423325b8cd15d
