### ISSUE TITLE
Pr2: hay 2 soluciones para `agregarAlFinal`

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#11]
No es feliz ofrecer más de una solución sin elegir alguna, o sin establecer las ventajas y desventajas de cada una de ellas. Eso muestra indecisión y acá se trata de poder tomar decisiones...

**Comment by ramirez7358** [comment]
La elimine.

0bda335c0075d0d49a55fb3a93e423325b8cd15d

**Comment by fidel-ml** [comment]
Si querés conservarla para una cuestión de estudio o recordar lo que no hay que hacer, comentala. ;)
