### ISSUE TITLE
Pr2: la función `zipMaximos` no es totalmente correcta

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#12]
Básicamente, pierde elementos. Los elementos que sobran en cualquiera de las 2 listas deberían ser parte de la solución (o sea, en ese sentido esta función no es igual a `zip`).

**Comment by ramirez7358** [comment]
Corregido en:

4820c6322ada2ea3471ebb31a6c331b0b937ca16
