### ISSUE TITLE
Pr 2: en `proyectosSinRepetidos ` estás mirando la pertenencia contra una lista más larga de lo necesaria

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#15]
Al usar `ps` en lugar de `proyectosSinRepetidos ps` en la condición, mirás más veces de las necesarias.
Esto es en general para cuando querés remover duplicados...

Este tema lo vimos en clase...

**Comment by ramirez7358** [comment]
Corregido en b0af8716925ec8c1745e622e1afee8b711e41111

**Comment by fidel-ml** [comment]
Fijate que ahora estás llamando dos veces a la recursión... Se puede hacer mejor aún si usás subtareas. ¿Recordás que este tema lo discutimos en el pizarrón en clase? ;)

**Comment by ramirez7358** [comment]
Perfecto, agregue una subtarea para agregar un proyecto a una lista, solo si no esta en la lista.
La lista que le paso son los proyectos sin repetidos.

7f2f2a70ec6dfe11188855a48484c91faeebf781
