### ISSUE TITLE
Pr2: el segundo caso de `losQueTrabajanEn` es innecesario

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#17]
NUNCA hagas doble PM si no es necesario. Y SIEMPRE agotá los casos de un parámetro antes de mirarel otro... (cuando es necesario mirarlo, que no es este caso).

**Comment by ramirez7358** [comment]
Corregido en b0af8716925ec8c1745e622e1afee8b711e41111
