### ISSUE TITLE
Pr2: en `asignadosPorProyecto` estás repitiendo muchas veces cada proyecto...

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#18]
O sea, si un proyecto `p` particular aparece 3 veces, ponés 3 elementos `(p,3)` en la lista final, y esto no es feliz.
Además, estás recorriendo muchísimas veces todos los proyectos de la empresa, lo que no es muy bueno.
La idea es usar recursión estructural sobre los proyectos de la empresa...

**Comment by ramirez7358** [comment]
Corregido en b0af8716925ec8c1745e622e1afee8b711e41111

**Comment by fidel-ml** [comment]
Ahora estás recorriendo muchísimas veces la empresa, una vez por cada proyecto, después de haberla recorrido muchas veces para sacar los repetidos. NO es la forma en que debe pensarse. Probá usar RECURSIÓN ESTRUCTURAL y así no tener que recorrer 700 veces...

**Comment by ramirez7358** [comment]
Me costo pensarlo como lo tenia, asi que lo borre y lo empece de nuevo. Deje la vieja solucion comentada como mal.
Lo que hago ahora es recorrer los roles e ir agregandolos o sumando uno en la tupla que le corresponde.

930125ee0d38fa533000d7c779f614fa8cea34a8
