### ISSUE TITLE
La función vieneDespues es incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#2]
La función `vieneDespues` definida no es la pedida. Por ejemplo, `Miercoles` viene después que `Lunes`, pero tu función no lo indica adecuadamente, porque solamente considera el caso inmediato siguiente, y no todos.

Atención al corregirla de no caer en una explosión combinatoria de casos. El consejo es usar subtareas adecuadas.

**Comment by ramirez7358** [comment]
Perfecto ya lo corregí. Muchas gracias.

**Comment by fidel-ml** [comment]
Pero ahora usa una característica prohibida en esta materia... Mirá el issue #3

**Comment by ramirez7358** [comment]
https://github.com/ramirez7358/EstrD22s1-Brian-Ramirez/commit/be90d3f04c33f03444b74f7d9f0028ff2a7d9a5b
