### ISSUE TITLE
Pr3: `ponerN` es innecesariamente compleja e incorrecta

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#20]
¿Por qué hacer recursión sobre AMBOS parámetros, si alcanza con hacerlo sobre UNO SOLO?
Esto te lleva a equivocarte en la cantidad de bolitas que pone... ¿La probaste?

**Comment by ramirez7358** [comment]
89ebd1f510b5790182c0b501e7b7ca5556971dbd

**Comment by fidel-ml** [comment]
Mucho mejor. Fijate que si cambiamos el constructor de `Bolita` deja de funcionar. Pero si usás otra subtarea que ya tenés, te evitás tener que arreglarla en ese caso :)
Es un detalle, igual
