### ISSUE TITLE
Pr3: `ramaMasLarga` no está hecha estrictamente por recursión estructural

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#24]
Al utilizar una función auxiliar sobre los subárboles, se pierde la idea de recursión estructural (y se trabaja de más).
Pensá por recursión estructural... (y subtareas)

**Comment by ramirez7358** [comment]
Agregue una sub tarea que compara dos listas y devuelve la mas larga.
A esta sub tarea le mando ramaMasLarga de t1 y ramaMasLarga de t2.

La vieja solucion pensada sobre nodos y no sobre listas, la deje comentada.
89ebd1f510b5790182c0b501e7b7ca5556971dbd
