### ISSUE TITLE
Pr3: `simplificarNegacion` no es correcta

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#25]
Porque es una auxiliar que debe ARMAR una negación según sea el argumento. Y lo que hace es sacar doble negación directamente, sin agregar nada, por lo que cambia el significado...
Funciona por propiedades accidentales de la negación, pero no es feliz que sea así.

**Comment by ramirez7358** [comment]
Corregido en 89ebd1f510b5790182c0b501e7b7ca5556971dbd
