### ISSUE TITLE
La función `vieneDespues2` utiliza una característica que no hay para `DiaDeLaSemana`

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#3]
NO está permitido usar la característica `deriving` en algo diferente de la clase `Show` (en esta materia).

**Comment by ramirez7358** [comment]
Elimine vieneDespues2

**Comment by fidel-ml** [comment]
Pero SEGUÍS teniendo el `deriving (Eq, Ord)` y dependiendo de él. ESO es lo que está mal...

**Comment by ramirez7358** [comment]
Eliminado en https://github.com/ramirez7358/EstrD22s1-Brian-Ramirez/commit/be90d3f04c33f03444b74f7d9f0028ff2a7d9a5b
