### ISSUE TITLE
Funciones and y or diferentes a las pedidas. 

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#4]
La función `and` de la práctica 1 debería comportarse de la siguiente manera:
```
> and False (error "Mal")
False
```
Sin embargo, tu versión da `error "Mal"`.
Así, no es la función pedida.

Exactamente lo mismo pasa con la función `or`, que debería pasar el test `or True (error "Mal")` dando `True`.

**Comment by ramirez7358** [comment]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/9968823/162034274-7f14caef-98c7-4a26-82be-cd4a13562f09.png">

Buenas Fidel, me dan bien los tests.

**Comment by fidel-ml** [comment]
Lo conversamos en clase. Funcionan por una característica poco feliz de Haskell. La idea es NO usar doble PM.

**Comment by ramirez7358** [comment]
Perfecto, con la explicacion en la clase de ayer me quedo claro. Lo corregi en be90d3f04c33f03444b74f7d9f0028ff2a7d9a5b
