### ISSUE TITLE
El tipo `Entrenador` está definido en forma levemente ineficaz

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#6]
No es necesario que el tipo `Entrenador` tenga un par de `Pokemon`. Puede tener ambos Pokemon directamente, sin el par.
Eso te complica después las funciones...

**Comment by ramirez7358** [comment]
Aplique el cambio al tipo `Entrenador` y a las funciones que lo usan. Muchas gracias
