### ISSUE TITLE
La función `juntarPokemon` es ineficaz

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#7]
Básicamente, si se cambia la definición de entrenador, se te complica esta función...
Además, al mirar a los dos al mismo tiempo estás repitiendo trabajo que debería ser para subtareas.
Finalmente, si bien no está mal usar `fst` y `snd`, estaría bueno que practiques el uso de PM, porque lo vamos a usar mucho...

**Comment by ramirez7358** [comment]
Entiendo, cambie por PM en esta funcion y cambie otras funciones que seguian implementando a los Pokemon como par.

7cac552456948f4e9095779090510d1ec5805439

**Comment by fidel-ml** [comment]
Ahora te fuiste del otro lado. Podrías haber usado un pattern para el par... `juntarPokemon (e1,e2)` y te ahorrás el `fst` y `snd`.
