### ISSUE TITLE
Pr2: tus funciones `and'` y `or'` son inadecuadas porque usan doble PM

### ISSUE THREAD

**Issue by fidel-ml** [ramirez7358/EstrD22s1#8]
Lo trabajamos en la práctica 1, y se supone que no vuelvan a cometer los mismos errores...
Un truco para hacer eso es REUTILIZAR, en lugar de reinventar todo cada vez...

**Comment by fidel-ml** [comment]
De hecho, son auxiliares para `conjuncion` y `disyuncion` donde podrías utilizar los operadores predefinidos `(&&)` y `(||)`.

**Comment by ramirez7358** [comment]
Me quedo el copy paste antes de las correcciones de la practica 1.

Dejo link a las correciones:

0bda335c0075d0d49a55fb3a93e423325b8cd15d
